import Head from "next/head";
import Image from "next/image";
import { Parallax, useParallax } from "react-scroll-parallax";
import Layout from "../components/layout/Layout";
import heroImage from "../public/images/hero.jpg";
import { motion } from "framer-motion";
import { useState } from "react";

export default function Home() {
  const [visible, setVisible] = useState(false);
  function handleAnimation() {
    setVisible(!visible);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="text-gray-100 bg-gray-800">
          <div className="h-screen w-full">
            <Parallax
              speed={-40}
              className="h-full w-full pt-20 relative flex justify-center items-center"
            >
              <Image src={heroImage} layout="fill" objectFit="cover" priority />
              <Parallax
                speed={40}
                className="overflow-hidden w-full text-secondary-400 text-8xl relative font-bold flex flex-col items-center p-8 rounded"
              >
                <motion.h1
                  animate={{ x: visible ? -100 : -1800 }}
                  transition={{ duration: 0.8, type: "spring" }}
                >
                  Jump straight into
                </motion.h1>
                <motion.h1
                  animate={{ x: visible ? 50 : 1800 }}
                  transition={{ delay: 0.2, duration: 0.8, type: "spring" }}
                >
                  your next adventure
                </motion.h1>
                <button onClick={handleAnimation}>Animate</button>
              </Parallax>
            </Parallax>
          </div>

          <div className="h-screen bg-gray-800 relative">Content</div>
        </main>
      </Layout>
    </>
  );
}
